@startuml
' CAMBIO EN RAMA MAIN PARA CREAR CONFLICTO
' CAMBIO DESDE RAMA HISTORIA-USUARIO PARA CREAR CONFLICTO

skinparam classAttributeIconSize 0

class Socio {
  - idSocio : int
  - dni : string
  - nombre : string
  - estado : string
  - fechaSuspensionFin : date
  --
  + solicitarPrestamo()
  + devolverLibro()
}

class Libro {
  - idLibro : int
  - titulo : string
  - estado : string
  - stock : int
  --
  + verificarDisponibilidad()
  + descontarEjemplar()
}

class Prestamo {
  - idPrestamo : int
  - fechaPrestamo : date
  - fechaDevolucion : date
  - estado : string
  --
  + registrarPrestamo()
  + marcarDevolucion()
  + verificarVencimiento()
}

@enduml

